cc_library(
	name= "util",
	visibility = ["//visibility:public"],
	hdrs = [
		"cuda_check.hh",
		"overload_set.hh",
		"fmt_quantity.hh",
		"soa_allocator.cu.hh",
	],
	srcs = ["soa_allocator_impl.cu.hh"],
)
